#!/bin/sh
case "$1" in
  info)
      versionCurrent=$(cat /etc/config/addons/cuxd/VERSION)
      versionUpdate=$(cat /etc/config/addons/cuxd/versionUpdate)
      echo "Info: <center><b>CUx-Daemon $VER</b><br><img src="../addons/cuxd/CUXD.PNG"></center>"
      echo "Name: CUx-Daemon"
      echo "Version: $versionCurrent"

      if [ "$versionCurrent" != "$versionUpdate" ]
      then
        echo "Update: /addons/cuxd/update-check.cgi"
      fi
  ;;
esac

exit 0
