#! /bin/bash
### BEGIN INIT INFO
# Provides: rfd
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: homematic ccu
### END INIT INFO
case "$1" in
  'start')
        /opt/ccu-start.sh
    ;;
  'stop')
	/opt/ccu-stop.sh
    ;;
  *)
        echo "Usage: /etc/init.d/ccu {start|stop}"
        exit 1
    ;;
esac
exit 0
