#! /bin/bash
### BEGIN INIT INFO
# Provides: rfd
# Required-Start: $network
# Required-Stop:
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: homematic ccu
### END INIT INFO

start()
{
	for i in /etc/init.d/S??*
	do
        	$i start
	done
}

stop()
{
	for i in /etc/init.d/S??*
	do
        	$i stop
	done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit 0
