#!/bin/bash

start()
{
	if [[ -e /var/status/HMIPenabled ]]
	then
		hmipdevice=`cat /var/status/HMIPenabled`

		if [[ $hmipdevice == *"tty"* ]]; then
			modprobe cp210x
			sh -c 'echo 1b1f c020 > /sys/bus/usb-serial/drivers/cp210x/new_id'
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyS0/Adapter.1.Port=\/dev\/'$hmipdevice'/g' /etc/config/crRFD.conf
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyUSB0/Adapter.1.Port=\/dev\/'$hmipdevice'/g' /etc/config/crRFD.conf
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyUSB1/Adapter.1.Port=\/dev\/'$hmipdevice'/g' /etc/config/crRFD.conf
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyS1000/Adapter.1.Port=\/dev\/'$hmipdevice'/g' /etc/config/crRFD.conf
		else
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyS0/Adapter.1.Port=\/dev\/ttyS1000/g' /etc/config/crRFD.conf
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyUSB0/Adapter.1.Port=\/dev\/ttyS1000/g' /etc/config/crRFD.conf
			/bin/sed -i 's/Adapter.1.Port=\/dev\/ttyUSB1/Adapter.1.Port=\/dev\/ttyS1000/g' /etc/config/crRFD.conf
			/usr/bin/socat -d pty,link=/dev/ttyS1000,raw openssl-connect:$hmipdevice:2000,cert=/etc/ssl/homematic-socat/client.crt,key=/etc/ssl/homematic-socat/client.key,cafile=/etc/ssl/homematic-socat/server.crt,forever,commonname= &

        	        for i in $(seq 1 60)
	                do
                	        sleep 1
        	                PID=`pidof socat`
	                        if [[ ${PID} != "" ]]
                        	then
                	                break
        	                fi
	                done
		fi
	fi

	rm -rf /usr/local/tmp/*
	rm -f /var/tmp/*
	rm -f /var/status/HMServerStarted
	rm -f /opt/java/bin/java
	ln -s $(which java) /opt/java/bin/

	#Check CCU updates
	git -C /opt/occu/ pull
	git -C /opt/occu-x86/ pull

	versionOCCU=`git -C /opt/occu/ describe --tags`
	versionX86=`git -C /opt/occu-x86/ describe --tags`
	versionCombined=$versionOCCU" / "$versionX86
	echo "homematic.com.setLatestVersion('"$versionCombined"', 'HM-CCU3');" > /www/ccuupdate.txt
}

stop()
{
        killall socat

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof socat`

                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

