#!/bin/bash

start()
{
        if [[ -e /etc/config/crRFD.conf ]]
        then
                hmipdevice=`cat /etc/config/crRFD.conf`

                if [[ $hmipdevice == *"tty"* ]]
                then
                        if [[ $hmipdevice == *"S1000"* ]]
                        then
                                sleep 20
#                                /usr/bin/socat -d pty,link=/dev/ttyS1000,raw tcp-connect:192.168.0.4:2200 &
                               /usr/bin/socat -d pty,link=/dev/ttyS1000,raw openssl-connect:192.168.0.107:2000,cert=/etc/ssl/homematic-socat/client.crt,key=/etc/ssl/homematic-socat/client.key,cafile=/etc/ssl/homematic-socat/server.crt,forever,commonname= &
                        else
                                modprobe cp210x
                                sh -c 'echo 1b1f c020 > /sys/bus/usb-serial/drivers/cp210x/new_id'
                        fi
                fi
        fi

	rm -rf /usr/local/tmp/*
	rm -f /var/tmp/*
	rm -f /var/status/HMServerStarted
	rm -f /opt/java/bin/java
	ln -s $(which java) /opt/java/bin/

	#Check CCU updates
	/opt/ccu-update-check.sh
}

stop()
{
        killall socat

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof socat`

                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

