#!/bin/bash

start()
{
        /bin/hs485dLoader -l 0 -ds -dd /etc/config/hs485d.conf -ilp /etc/config/InterfacesList.xml #Updates Wired Interfaces
}

stop()
{
        killall hs485dLoader

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof hs485dLoader`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
	start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

