#!/bin/bash

start()
{
        /bin/hs485dLoader -dw /etc/config/hs485d.conf &
}

stop()
{
        killall hs485dLoader
        killall hs485d

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof hs485dLoader`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof hs485d`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
	start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

