#!/bin/bash
start()
{
        virt=`systemd-detect-virt`

        if ! [ $virt = "lxc" ]
        then
                echo 1 >/sys/class/raw-uart/raw-uart/reset_radio_module
                modprobe hb_rf_usb
                modprobe eq3_char_loop
                modprobe generic_raw_uart
	fi

        /bin/multimacd -f /etc/config/multimacd.conf -l 2 &

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof multimacd`
                if [[ ${PID} != "" ]]
                then
                        break
                fi
        done

        if [ $virt = "lxc" ]
        then
                for i in $(seq 1 20)
                do
                        sleep 1

                        if [ -d "/sys/devices/virtual/eq3loop/mmd_bidcos" ]
                        then
                                id=`cat /sys/devices/virtual/eq3loop/mmd_bidcos/dev`
                                id=${id//:/ }
                                mknod /dev/mmd_bidcos c $id
                                break
                        fi
                done

                for i in $(seq 1 20)
                do
                        sleep 1

                        if [ -d "/sys/devices/virtual/eq3loop/mmd_hmip" ]
                        then
                                id=`cat /sys/devices/virtual/eq3loop/mmd_hmip/dev`
                                id=${id//:/ }
                                mknod /dev/mmd_hmip c $id
                                break
                        fi
                done
        fi
}

stop()
{
        killall multimacd

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof multimacd`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?
