#!/bin/bash
start()
{
        virt=`systemd-detect-virt`

        if [ $virt = "lxc" ]
        then
                echo 1 >/sys/class/raw-uart/raw-uart/reset_radio_module
                modprobe hb_rf_usb
                modprobe eq3_char_loop
                modprobe generic_raw_uart
	fi

        /bin/multimacd -f /etc/config/multimacd.conf -l 2 &

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof multimacd`
                if [[ ${PID} != "" ]]
                then
                        break
                fi
        done

        if [ $virt = "lxc" ]
        then
                for i in $(seq 1 20)
                do
                        sleep 1

                        if [ -d "/sys/devices/virtual/eq3loop/mmd_bidcos" ]
                        then
                                data=`udevadm info -q property /sys/devices/virtual/eq3loop/mmd_bidcos`
                                data=`echo -n $data`
                                temp=${data#*MAJOR=}
                                major=${temp%% *}
                                temp=${data#*MINOR=}
                                minor=${temp%% *}
                                temp=${data#*DEVNAME=}
                                device=${temp%% *}
                                path=${device%/*}
                                mkdir -p $path
                                mknod $device c $major $minor
                                break
                        fi
                done

                for i in $(seq 1 20)
                do
                        sleep 1

                        if [ -d "/sys/devices/virtual/eq3loop/mmd_hmip" ]
                        then
                                data=`udevadm info -q property /sys/devices/virtual/eq3loop/mmd_hmip`
                                data=`echo -n $data`
                                temp=${data#*MAJOR=}
                                major=${temp%% *}
                                temp=${data#*MINOR=}
                                minor=${temp%% *}
                                temp=${data#*DEVNAME=}
                                device=${temp%% *}
                                path=${device%/*}
                                mkdir -p $path
                                mknod $device c $major $minor
                                break
                        fi
                done
        fi
}

stop()
{
        killall multimacd

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof multimacd`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?
