#!/bin/bash

start()
{
	/bin/su -s /bin/bash -c "/bin/rfd -d -f /etc/config/rfd.conf -l 2 &"

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof rfd`
                if [[ ${PID} != "" ]]
                then
                        break
                fi
        done
}

stop()
{
        killall rfd

        for i in $(seq 1 20)
        do
                sleep 1
                PID=`pidof rfd`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

