#!/bin/bash

start()
{
        HMIPEnabled=`cat /etc/config/InterfacesList.xml`

        if [[ $HMIPEnabled == *"HmIP"* ]]
        then
                Data=`cat /etc/config/crRFD.conf`
                DataCut=${Data#*Adapter.1.Port=}
                HMIPDevice="${DataCut%%$'\n*'}"
                /bin/su -s /bin/bash -c "/usr/bin/java -server -Xms1024m -Xmx1024m -Dgnu.io.rxtx.SerialPorts=$HMIPDevice -Dlog4j.configuration=file:///etc/config/log4j.xml -jar /opt/HMServer/HMIPServer.jar /etc/config/crRFD.conf &"
        else
                /usr/bin/java -server -Xms1024m -Xmx1024m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -jar /opt/HMServer/HMServer.jar &
        fi

        for i in $(seq 1 30)
        do
                sleep 1
                if [[ -e /var/status/HMServerStarted ]]
                then
                        break
                fi
        done
}

stop()
{
        killall java

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof java`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

