#!/bin/bash

start()
{
        /bin/su -s /bin/bash -c "/bin/ReGaHss -f /etc/rega.conf -l 2 &"

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof ReGaHss`
                if [[ ${PID} != "" ]]
                then
                        break
                fi
        done
}

stop()
{
        killall ReGaHss

        for i in $(seq 1 60)
        do
                sleep 1
                PID=`pidof ReGaHss`
                if [[ ${PID} = "" ]]
                then
                        break
                fi
        done
}

restart()
{
        stop
        start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {stop}"
    exit 1
esac

exit $?

